max_width = 120
comment_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
fn_args_layout = "Tall"
force_explicit_abi = true
remove_nested_parens = true
# Unstable Features:
unstable_features = true
color = "Always"
binop_separator = "Back"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = false
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
report_fixme = "Always"
report_todo = "Always"
space_after_colon = true
space_before_colon = true
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = false
trailing_semicolon = true
type_punctuation_density = "Wide"
wrap_comments = true
group_imports = "One"